name: Build and Release Halo TFT LCD Firmware

env:
  DEVICE_NAME: halo

on:
  push:
    paths:
      - 'TFT_LCD/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the firmware to build'
        required: true
  release:
    types: [published]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only create a release on push
    permissions:
      contents: write  # Ensure permissions for writing to the repo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Get Version
        id: get_version
        run: |
          if [ -f "TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/Halo-v1-Core.yaml" ]; then
            version=$(awk '/substitutions:/ {found=1} found && /version:/ {print $2; exit}' TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/Halo-v1-Core.yaml | tr -d '"')
            if [ -n "$version" ]; then
              echo "project_version=$version" >> $GITHUB_ENV
              echo "Version extracted: $version"
            else
              echo "Error: Could not extract version from file"
              exit 1
            fi
          else
            echo "Error: Core file not found"
            exit 1
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use PAT for authentication
        with:
          tag_name: ${{ env.project_version }}
          release_name: "Release ${{ env.project_version }}"
          draft: false
          prerelease: false
          body: "Auto-generated release from GitHub Actions."

  build-firmware:
    name: Build And Release
    needs: [create-release, build-site]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install ESPHome
        run: |
          pip install esphome
          
      - name: Build Firmware
        run: |
          cd TFT_LCD/T-Display-Long/V1/Firmware/ESPHome
          esphome compile Halo-v1.yaml
          echo "Build completed. Checking for firmware files..."
          find .esphome/build -name "*.bin" -type f
          
      - name: Debug - Show Build Directory
        run: |
          cd TFT_LCD/T-Display-Long/V1/Firmware/ESPHome
          echo "Build directory structure:"
          ls -la .esphome/ || echo "No .esphome directory found"
          ls -la .esphome/build/ || echo "No build directory found"
          if [ -d ".esphome/build" ]; then
            echo "Build subdirectories:"
            ls -la .esphome/build/
            for dir in .esphome/build/*/; do
              if [ -d "$dir" ]; then
                echo "Contents of $dir:"
                ls -la "$dir"
                if [ -d "$dir.pioenvs" ]; then
                  echo "Contents of $dir.pioenvs:"
                  ls -la "$dir.pioenvs"
                  for pio_dir in "$dir.pioenvs"/*/; do
                    if [ -d "$pio_dir" ]; then
                      echo "Contents of $pio_dir:"
                      ls -la "$pio_dir"
                    fi
                  done
                fi
              fi
            done
          fi
          
      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: firmware-tft
          path: |
            TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/.esphome/build/*/.pioenvs/*/firmware.factory.bin
            TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/.esphome/build/*/.pioenvs/*/firmware.bin
            TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/.esphome/build/*/*.bin
            TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/.esphome/build/*/.pioenvs/*/manifest.json
          if-no-files-found: error

  build-site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7

      - name: Build Site
        uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: ./static
          destination: ./output

      - name: Upload Site Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: site
          path: output

  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - build-firmware
      - build-site
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Firmware Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: firmware-tft
          path: firmware

      - name: Check Firmware Artifacts
        run: |
          echo "Checking firmware artifacts..."
          ls -la firmware/ || echo "No firmware directory found"
          if [ -d "firmware" ]; then
            echo "Firmware files found:"
            find firmware -type f
          else
            echo "No firmware artifacts downloaded"
            exit 1
          fi

      - name: Copy Firmware and Manifest
        run: |-
          mkdir -p output/firmware
          cp -r firmware/* output/firmware/

      - name: Download Site Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: site
          path: output

      # ------------------- ADDED: Ensure manifest.json exists -------------------
      - name: Ensure manifest.json exists for Web Installer (non-breaking)
        working-directory: output/firmware
        env:
          CHIP_FAMILY: ESP32-S3            # change if your board differs
          DEVICE_NAME: ${{ env.DEVICE_NAME }}
        run: |
          set -euo pipefail
          # If a manifest already exists (from ESPHome build), leave it alone.
          if [ -f "manifest.json" ]; then
            echo "Existing manifest.json found. Using it as-is."
            exit 0
          fi

          echo "No manifest.json found in output/firmware. Generating a minimal one."

          # Prefer factory -> ota -> any .bin
          FACTORY="$(ls -1 **/*.factory.bin 2>/dev/null | head -n1 || true)"
          OTA="$(ls -1 **/*.ota.bin 2>/dev/null | head -n1 || true)"
          if [ -z "${OTA}" ]; then
            OTA="$(ls -1 **/firmware.bin 2>/dev/null | head -n1 || true)"
          fi
          if [ -z "${FACTORY}" ]; then
            FACTORY="$(ls -1 **/*.bin 2>/dev/null | grep -v '\.ota\.bin$' | head -n1 || true)"
          fi

          if [ -z "${FACTORY}" ]; then
            echo "ERROR: Could not find a factory .bin to reference."
            find . -type f
            exit 1
          fi

          # Compute md5 for OTA if present
          OTA_MD5=""
          if [ -n "${OTA}" ] && [ -f "${OTA}" ]; then
            OTA_MD5="$(md5sum "${OTA}" | awk '{print $1}')"
          fi

          VERSION="${GITHUB_REF_NAME:-latest}"

          # Create minimal manifest compatible with esp-web-tools
          # - If OTA is missing, we still produce a manifest with only 'parts'
          {
            echo '{'
            echo '  "name": "'${DEVICE_NAME}'.TFT-LCD",'
            echo '  "version": "'${VERSION}'",'
            echo '  "home_assistant_domain": "esphome",'
            echo '  "new_install_prompt_erase": false,'
            echo '  "builds": ['
            echo '    {'
            echo '      "chipFamily": "'${CHIP_FAMILY}'",'
            if [ -n "${OTA}" ]; then
              echo '      "ota": {'
              echo '        "path": "'${OTA}'",'
              if [ -n "${OTA_MD5}" ]; then
                echo '        "md5": "'${OTA_MD5}'",'
              fi
              echo '        "summary": ""'
              echo '      },'
            fi
            echo '      "parts": ['
            echo '        { "path": "'${FACTORY}'", "offset": 0 }'
            echo '      ]'
            echo '    }'
            echo '  ]'
            echo '}'
          } > manifest.json

          echo "Generated manifest.json:"
          cat manifest.json
      # ------------------------------------------------------------------------

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: output
          retention-days: 1

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
